"""
tools/health_summary.py — Compiles data into a neat report.

🎓 WHAT THIS DOES:
   This tool doesn't save anything new. Instead, it IMPORTS the data
   from the logging and reminder tools, and squashes them into a nice
   Markdown string that Gemini can show the user at the end of a week.
"""

from datetime import datetime
from typing import Dict, Any

# Import the helper functions we made in the other files
from tools.symptom_logger import get_all_symptoms
from tools.medication_reminder import get_all_active_reminders

def generate_health_summary(patient_name: str = "User") -> Dict[str, Any]:
    """
    Called by Gemini to generate a full health report.
    Returns a dictionary containing a pre-formatted markdown string.
    """
    symptoms = get_all_symptoms()
    reminders = get_all_active_reminders()
    
    now_str = datetime.now().strftime("%B %d, %Y (%H:%M)")

    # 1. Build the Header
    report_lines = [
        f"# 🏥 MediAssist Health Summary for {patient_name}",
        f"**Generated:** {now_str}",
        "---",
        ""
    ]

    # 2. Build the Symptoms Section
    report_lines.append("## 📋 Logged Symptoms")
    if len(symptoms) == 0:
        report_lines.append("- No symptoms logged yet.")
    else:
        # Loop through symptoms and format them nicely
        for s in symptoms:
            sev_str = f" *(Severity: {s['severity']}/10)*" if s.get("severity") else ""
            note_str = f" — {s['notes']}" if s.get("notes") else ""
            report_lines.append(f"- **{s['timestamp']}**: {s['symptom']}{sev_str}{note_str}")
            
    report_lines.append("\n--- \n")

    # 3. Build the Reminders Section
    report_lines.append("## 💊 Active Medication Reminders")
    if len(reminders) == 0:
        report_lines.append("- No active reminders.")
    else:
        for r in reminders:
            note_str = f" *(Note: {r['notes']})*" if r.get("notes") else ""
            report_lines.append(f"- **{r['medication']}** ({r['time']} — {r['frequency']}){note_str}")

    # 4. Add Medical Disclaimer
    report_lines.extend([
        "",
        "---",
        "> ⚠️ **Disclaimer**: This summary was generated by an AI assistant and is not an official medical record. Always consult a licensed healthcare provider."
    ])

    # 5. Join all the lines together with "newlines" (\n)
    final_markdown = "\n".join(report_lines)

    # 6. Send it back to Gemini
    return {
        "status": "success",
        "symptoms_found": len(symptoms),
        "reminders_found": len(reminders),
        "report_markdown": final_markdown
    }
